version: "3.0"

services:
    webapp:
      build:
        context: .  
      image: rufusmbugua/laravel
      container_name: rally_website
      ports:
      - 1080:80
      links:
        - db
        - adminer
      deploy:
        mode: replicated
        replicas: 3
        restart_policy:
          condition: on-failure
    
    db:
      image: mysql
      container_name: db
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: blog

    adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 90:8080
 
